Direct RUN based on previous setup if RUN_FROM_ARGSFILE is true
itzg/docker-minecraft-server pull request #1219
Opened 2021-12-22 00:30 UTC by tasarren

This helps building dependencies and running the server itself separately.

At first I thought `EXEC_DIRECTLY` and `SETUP_ONLY` were made for this purpose, but it only works if you copy stdout into your custom script.

With this changes, running `SETUP_ONLY` and `SAVE_RUNARGS` will create a `/data/runargs.txt` file that will be readed later by the same `/start` script if existing and if `RUN_FROM_ARGSFILE` is true.. skipping the whole script process and just run the server.

With this method we went from ~2 minutes server upgrade to just 10 seconds, because the whole dependency flow has been done by an initializer.

I am not sure how to merge everything into java8 and other branches to test it out, too many conflicts that I'm unaware of, so any guidance would be nice.

2021-12-22 02:13 UTC, itzg reviewed
This is an interesting idea. I'm good with merging it, but want to point out that of course it's faster startup time because it bypasses all upgrade checks. In a fixed VERSION scenario that's probably handy...except when something like the paper installer needs to be redownloaded to pick up a vulnerability fix like the recent Log4jShell. Users need to opt into and choose the shortcut, which is why I bring up the point but not as a blocker. 

Don't worry about the other variants. I'll take care of that merging and only the gosu usage needs to be addressed manually with the alpine variant.

2021-12-22 02:18 UTC, itzg commented
Can you add a section to the README near the SETUP_ONLY section?

2022-01-05 20:04 UTC, tasarren commented
Sorry for the delay. Let me know if some modifications are needed, English is not my language so I can make some spelling mistakes.

I've running my servers with this method lately and so far so good, let's hope it doesnt bring any bugs ^^

Happy new year :partying_face:

2022-01-08 00:31 UTC, itzg approved these changes

2022-01-08 00:31 UTC, itzg commented on README.md
> +**Use with caution**
I really appreciate the caution notice.

2022-01-08 01:27 UTC, itzg requested changes

2022-02-12 02:19 UTC, closed without merging