Support ketting hybrid server
itzg/docker-minecraft-server pull request #2535
Opened 2023-12-10 05:43 UTC by aruneko

Since maintaining of magma project [has been stopped](https://git.magmafoundation.org/magmafoundation/magma-1-20-x/-/commit/4e7abe37403c47d09b74b77bcfc26a19b18f5891), I will add a support Ketting server for MC 1.20.2+ hybrid server.

2023-12-10 17:52 UTC, itzg approved these changes
Thanks!

2023-12-10 17:54 UTC, itzg requested changes
...can you add a small note with the link you provided in the Magma section of the docs?

2023-12-11 11:03 UTC, aruneko commented
Sure, I have added that!

2023-12-11 13:19 UTC, itzg approved these changes

2023-12-11 13:19 UTC, merged