Allow to enable / disable whitelist without modifying the whitelist file
itzg/docker-minecraft-server pull request #937
Opened 2021-06-26 10:41 UTC by P4sca1

Currently there is no way to just enable the whitelist without adding a player to the whitelist file.
This change allows to set `WHITELIST=true` to set the server properties accordingly without modifying the whitelist file.
Players can then be added / removed from the whitelist using the `whitelist add` and `whitelist remove` commands.
For convenience `WHITELIST=false` will now disable the whitelist and has the same behaviour like `WHITELIST=` (empty string).

Signed-off-by: Pascal Sthamer <sthamer.pascal@gmail.com>

2021-06-26 17:14 UTC, itzg requested changes
Great idea, but let's simplify it a bit.

2021-06-26 17:14 UTC, itzg commented on start-finalSetupServerProperties
> +  if [ -n "$WHITELIST" && "$WHITELIST" != "false" ]; then
This is too confusing overloading `WHITELIST`. 

How about
```suggestion
  if [ -n "$WHITELIST" ] || isTrue ${ENABLE_WHITELIST:-false} ; then
```

2021-06-26 17:14 UTC, itzg commented on start-minecraftFinalSetup
> +if [ -n "$WHITELIST" && "$WHITELIST" != "true" && "$WHITELIST" != "false" ]; then
...then can just revert this to
```suggestion
if [ -n "$WHITELIST" ]; then
```

2021-06-27 11:21 UTC, P4sca1 commented
I like the idea of introducing a new `ENABLE_WHITELIST` env variable.
I have pushed another commit to address your suggestion.

2021-06-27 13:12 UTC, itzg approved these changes
Thanks!

2021-06-27 13:12 UTC, merged